-- V147: 给 mate_model_provider.id 补 AUTO_INCREMENT(MySQL)。
--
-- 背景:V1 baseline 的 mate_model_provider 以 provider_id 为主键、无 id 列;V133 在 MySQL 上用
-- `ADD COLUMN id BIGINT NULL` + 哈希回填 + 改主键(id),但【漏了 AUTO_INCREMENT】。而 H2 的 V133
-- 是重建表、id 用 `GENERATED BY DEFAULT AS IDENTITY`(自动生成)。于是裸 SQL 种子 data-mysql-zh.sql
-- 的 36 条 `INSERT INTO mate_model_provider (provider_id, ...)`(省略 id,与 H2 种子一致)在 MySQL 上
-- 报 `Field 'id' doesn't have a default value` → DatabaseBootstrapRunner 失败 → 后端起不来。
--
-- 修复:把 id 补成 AUTO_INCREMENT(与 H2 IDENTITY 行为对齐)。应用层(MyBatis-Plus)仍会显式赋雪花
-- id,AUTO_INCREMENT 列接受显式值、并把计数器跟到 max(id)+1,二者不冲突。id 为单列主键,满足
-- AUTO_INCREMENT 必须为键的约束。幂等:已是 auto_increment 则跳过(支持 flyway repair 后重跑场景)。
SET @ai := (SELECT EXTRA FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'mate_model_provider'
              AND COLUMN_NAME = 'id');
SET @s := IF(@ai IS NULL OR LOCATE('auto_increment', @ai) = 0,
             'ALTER TABLE mate_model_provider MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT',
             'SELECT 1');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
