-- V147: H2 上为 no-op。
--
-- mate_model_provider.id 在 H2 的 V133 重建表时已定义为
-- `BIGINT GENERATED BY DEFAULT AS IDENTITY ... PRIMARY KEY`(自动生成),裸 SQL 种子省略 id 即自增,
-- 无需改动。本文件仅为与 mysql/V147(给 id 补 AUTO_INCREMENT)保持迁移版本同步(见 CLAUDE.md:
-- h2/ 与 mysql/ 的每个 Vn 必须成对存在)。
SELECT 1;
