import { describe, expect, it } from 'vitest'
import leadPage from '../LeadAcquisition/index.vue?raw'
import livePanel from '../../components/lead/LeadRunLivePanel.vue?raw'
import finalSummary from '../../components/lead/LeadRunFinalSummary.vue?raw'
import runResult from '../../components/lead/DouyinLeadRunResult.vue?raw'
import api from '../../api/index.ts?raw'
import chatConsole from '../ChatConsole.vue?raw'
import router from '../../router/index.ts?raw'
import settingsLayout from '../Settings/Layout.vue?raw'

describe('lead acquisition experience', () => {
  it('offers a business-first Douyin lead workflow page', () => {
    expect(leadPage).toContain('获客专家')
    expect(leadPage).toContain('抖音获客')
    expect(leadPage).toContain('leadAcquisitionApi.startDouyinRun(payload)')
    expect(leadPage).toContain('常用模板')
    expect(leadPage).toContain('保存当前')
    expect(leadPage).toContain('模板名称')
    expect(leadPage).toContain('savedTemplates')
    expect(leadPage).toContain('loadTemplates')
    expect(leadPage).toContain('saveCurrentTemplate')
    expect(leadPage).toContain('deleteTemplate')
    expect(leadPage).toContain('评论匹配目标')
    expect(leadPage).toContain('描述匹配哪些评论')
    expect(leadPage).toContain('有意向的客户')
    expect(leadPage).toContain('体验不好的用户')
    expect(leadPage).toContain('matchDescription')
    expect(leadPage).toContain('matchExamples')
    expect(leadPage).not.toContain('执行环境')
    expect(leadPage).toContain('最近任务')
    expect(leadPage).toContain('线索池')
    expect(leadPage).toContain('统计看板')
    expect(leadPage).toContain('失败原因分布')
    expect(leadPage).toContain('stats-card-grid')
    expect(leadPage).toContain('failure-list')
    expect(leadPage).toContain('loadLeadStats')
    expect(leadPage).toContain('statsError')
    expect(leadPage).toContain('统计读取失败，点击刷新重试')
    expect(leadPage).toContain('loadLeadStats({ force: true })')
    expect(leadPage).toContain('leadAcquisitionApi.getDouyinStats')
    expect(leadPage).toContain('leadAcquisitionApi.listDouyinRuns')
    expect(leadPage).toContain('leadAcquisitionApi.listDouyinLeads')
    expect(leadPage).toContain('openRunFromHistory')
    expect(leadPage).toContain('leadPoolRows')
    expect(leadPage).toContain('leadPoolKeyword')
    expect(leadPage).toContain('leadPoolStatus')
    expect(leadPage).toContain('@keyup.enter="loadLeadPool"')
    expect(leadPage).toContain('@change="loadLeadPool"')
    expect(leadPage).toContain('回看任务')
    expect(leadPage).not.toContain('currentRun.value?.matches ?? []')
    expect(leadPage).not.toContain('engagementByCommentId')
    expect(leadPage).toContain('<BrowserPairingPanel embedded compact />')
    expect(leadPage).toContain('const browserPanelOpen = ref(false)')
    expect(leadPage).toContain('v-if="browserPanelOpen"')
    expect(leadPage).toContain('function openBrowserPanel')
    expect(leadPage).toContain('function closeBrowserPanel')
    expect(leadPage).toContain('<LeadRunLivePanel')
    expect(leadPage).toContain('@update:run="handleLiveRunUpdate"')
    expect(leadPage).toContain("mcToast.success('抖音获客任务已启动')")
    expect(leadPage).not.toContain("router.push('/settings/browser')")
  })

  it('starts Douyin acquisition into a realtime run panel', () => {
    expect(leadPage).toContain('const activeRunRunning = computed')
    expect(leadPage).toContain('const taskLocked = computed')
    expect(leadPage).toContain('const launchButtonText = computed')
    expect(leadPage).toContain('currentRun.value = normalizeRun(run)')
    expect(leadPage).toContain('LeadRunLivePanel')
  })

  it('exposes the Douyin run event stream API contract', () => {
    expect(api).toContain('streamDouyinRunEventsUrl')
    expect(api).toContain('/lead-acquisition/runs/${runId}/events/stream')
    expect(api).toContain('/lead-acquisition/douyin/leads')
    expect(api).toContain('/lead-acquisition/douyin/stats')
    expect(api).toContain('DouyinLeadStatsResponse')
    expect(api).toContain('getDouyinStats')
    expect(api).toContain('DouyinLeadPoolItem')
    expect(api).toContain('DouyinLeadTemplate')
    expect(api).toContain('listDouyinTemplates')
    expect(api).toContain('/lead-acquisition/douyin/templates')
    expect(api).toContain("params.set('token', token)")
    expect(api).toContain("params.set('afterEventId', String(afterEventId))")
  })

  it('renders realtime progress with SSE fallback and final summary', () => {
    expect(livePanel).toContain('new EventSource(url)')
    expect(livePanel).toContain('lead.comments.collecting')
    expect(livePanel).toContain('lead.engagement.completed')
    expect(livePanel).toContain('查看完整时间线')
    expect(livePanel).toContain('timeline-scroll')
    expect(livePanel).toContain('搜索与排序')
    expect(livePanel).toContain('线索触达')
    expect(livePanel).toContain('已自动改用定时刷新')
    expect(livePanel).toContain('window.setInterval')
    expect(livePanel).toContain('leadAcquisitionApi.getDouyinRun')
    expect(livePanel).toContain('LeadRunFinalSummary')
    expect(finalSummary).toContain('最终汇总')
    expect(finalSummary).not.toContain('技术明细')
    expect(runResult).toContain('展开评论明细')
    expect(runResult).toContain('panel-scroll-body')
  })

  it('retires the old browser settings entry after moving pairing into acquisition', () => {
    expect(settingsLayout).not.toContain("path: '/settings/browser'")
    expect(settingsLayout).not.toContain("id: 'browser'")
    expect(router).not.toContain("name: 'SettingsBrowser'")
    expect(router).toContain("{ path: 'settings/browser', redirect: '/lead-acquisition' }")
  })

  it('lets the lead expert chat surface start from a Douyin lead prompt', () => {
    expect(chatConsole).toContain('function isLeadExpertAgent')
    expect(chatConsole).toContain('function douyinLeadStarterPrompt')
    expect(chatConsole).toContain('确认后执行抖音获客，并在结束时汇总')
    expect(chatConsole).toContain('pendingRoutePrompt')
  })
})
